site_name: LP Test


repo_name: LP_test
repo_url: https://github.com/bielrossi15/LP_test

edit_uri: ""

extra_css:
  - stylesheets/extra.css

theme:
  name: material

  logo: stylesheets/assets/logo.png

  favicon: stylesheets/assets/logo.png

  icon:
    repo: fontawesome/brands/github
  
extra_css:
  - stylesheets/extra.css


